# Generated by Django 4.1.3 on 2022-11-02 07:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RGB",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "r",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[django.core.validators.MaxValueValidator(255)],
                    ),
                ),
                (
                    "g",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[django.core.validators.MaxValueValidator(255)],
                    ),
                ),
                (
                    "b",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[django.core.validators.MaxValueValidator(255)],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RGBA",
            fields=[
                (
                    "rgb_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="complementary.rgb",
                    ),
                ),
                (
                    "a",
                    models.PositiveSmallIntegerField(
                        default=255,
                        validators=[django.core.validators.MaxValueValidator(255)],
                    ),
                ),
            ],
            bases=("complementary.rgb",),
        ),
    ]
